#!/usr/bin/env node
/**
 * generate-index.js
 * Run:  node generate-index.js
 *
 * Reads all .html files in the current folder, groups them by slug prefix,
 * then writes  index.html  +  style.css  +  script.js
 */

const fs = require('fs');

// ─── HELPERS ──────────────────────────────────────────────────────────────────
const FILE_RE = /^(.*?)-(\d+)-(.+)\.html$/;

function toTitle(slug) {
  return slug.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

function parseFilename(filename) {
  const m = filename.match(FILE_RE);
  if (!m) return null;
  return { file: filename, groupSlug: m[1], id: m[2], name: toTitle(m[3]) };
}

// ─── READ + PARSE ─────────────────────────────────────────────────────────────
const dir = process.cwd();
const files = fs
  .readdirSync(dir)
  .filter((f) => f.endsWith('.html') && f !== 'index.html')
  .map(parseFilename)
  .filter(Boolean);

if (files.length === 0) {
  console.error('No matching .html files found in', dir);
  process.exit(1);
}

// ─── GROUP ────────────────────────────────────────────────────────────────────
const groupMap = {};
for (const f of files) {
  if (!groupMap[f.groupSlug])
    groupMap[f.groupSlug] = {
      slug: f.groupSlug,
      name: toTitle(f.groupSlug),
      items: [],
    };
  groupMap[f.groupSlug].items.push({ id: f.id, name: f.name, file: f.file });
}

const groups = Object.values(groupMap).map((g) => {
  g.items.sort((a, b) => parseInt(a.id) - parseInt(b.id));
  return g;
});

console.log(`Found ${files.length} files in ${groups.length} groups:`);
groups.forEach((g) =>
  console.log(`  [${String(g.items.length).padStart(2)}] ${g.name}`),
);

// ─── index.html ───────────────────────────────────────────────────────────────
const html = [
  '<!DOCTYPE html>',
  '<html lang="en">',
  '<head>',
  '  <meta charset="UTF-8" />',
  '  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>',
  '  <title>System Design Interview &mdash; Index</title>',
  '  <link rel="stylesheet" href="style.css" />',
  '</head>',
  '<body>',
  '<div class="wrap">',
  '',
  '  <header>',
  `    <p class="header-eyebrow">// ${files.length} files &middot; ${groups.length} groups</p>`,
  '    <h1>System Design<span>.</span></h1>',
  '    <p class="header-sub">Interview Reference Index</p>',
  '  </header>',
  '',
  '  <div class="controls">',
  '    <div class="search-box">',
  '      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">',
  '        <circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/>',
  '      </svg>',
  '      <input id="search" type="text" placeholder="Search files&hellip; (press /)" autocomplete="off" />',
  '    </div>',
  '    <div class="sort-btns">',
  '      <button class="sort-btn active" data-sort="id">Sort: ID</button>',
  '      <button class="sort-btn"        data-sort="name">Sort: Name</button>',
  '    </div>',
  '  </div>',
  '',
  '  <div class="group-tabs" id="tabs"></div>',
  '',
  '  <div class="stats-bar">',
  '    Showing <strong id="stats-count">0</strong> files',
  '  </div>',
  '',
  '  <div id="sections"></div>',
  '  <p id="empty">No files match your search.</p>',
  '',
  '  <footer>',
  '    <span>System Design Index</span>',
  '    <span id="footer-date"></span>',
  '  </footer>',
  '</div>',
  '<script src="script.js"></script>',
  '</body>',
  '</html>',
].join('\n');

// ─── style.css ────────────────────────────────────────────────────────────────
const css = [
  '/* style.css — generated by generate-index.js */',
  "@import url('https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&family=JetBrains+Mono:wght@300;400;500&display=swap');",
  '',
  '*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }',
  '',
  ':root {',
  '  --bg:       #0d0d10;',
  '  --surface:  #13131a;',
  '  --surface2: #1a1a24;',
  '  --border:   #22222e;',
  '  --text:     #e2e2ec;',
  '  --muted:    #50505e;',
  '  --c0: #f0a05a;',
  '  --c1: #5ac8f0;',
  '  --c2: #a05af0;',
  '  --c3: #5af0a0;',
  '  --c4: #f05a8a;',
  '}',
  '',
  'html { font-size: 16px; }',
  '',
  'body {',
  '  background: var(--bg);',
  '  color: var(--text);',
  "  font-family: 'JetBrains Mono', monospace;",
  '  min-height: 100vh;',
  '}',
  '',
  'body::before {',
  "  content: '';",
  '  position: fixed; inset: 0; z-index: 0;',
  '  background-image:',
  '    linear-gradient(var(--border) 1px, transparent 1px),',
  '    linear-gradient(90deg, var(--border) 1px, transparent 1px);',
  '  background-size: 40px 40px;',
  '  opacity: 0.3;',
  '  pointer-events: none;',
  '}',
  '',
  '.wrap {',
  '  position: relative; z-index: 1;',
  '  max-width: 1100px; margin: 0 auto; padding: 0 28px 96px;',
  '}',
  '',
  '/* HEADER */',
  'header { padding: 64px 0 48px; }',
  '.header-eyebrow { font-size: 10px; letter-spacing: 0.22em; text-transform: uppercase; color: var(--muted); margin-bottom: 18px; }',
  "h1 { font-family: 'Syne', sans-serif; font-size: clamp(36px,6vw,64px); font-weight: 800; line-height: 1; letter-spacing: -0.03em; margin-bottom: 8px; }",
  'h1 span { opacity: 0.25; }',
  '.header-sub { font-size: 12px; color: var(--muted); letter-spacing: 0.06em; }',
  '',
  '/* CONTROLS */',
  '.controls { display: flex; flex-wrap: wrap; gap: 10px; align-items: center; margin-bottom: 28px; }',
  '.search-box { position: relative; flex: 1; min-width: 220px; }',
  '.search-box svg { position: absolute; left: 14px; top: 50%; transform: translateY(-50%); color: var(--muted); pointer-events: none; }',
  "#search { width: 100%; background: var(--surface); border: 1px solid var(--border); color: var(--text); font-family: 'JetBrains Mono', monospace; font-size: 13px; padding: 11px 14px 11px 40px; outline: none; transition: border-color 0.2s; }",
  '#search:focus { border-color: var(--muted); }',
  '#search::placeholder { color: var(--muted); }',
  '.sort-btns { display: flex; gap: 6px; }',
  ".sort-btn { background: var(--surface); border: 1px solid var(--border); color: var(--muted); font-family: 'JetBrains Mono', monospace; font-size: 10px; letter-spacing: 0.12em; text-transform: uppercase; padding: 11px 16px; cursor: pointer; transition: all 0.15s; }",
  '.sort-btn:hover, .sort-btn.active { color: var(--text); border-color: var(--muted); }',
  '',
  '/* TABS */',
  '.group-tabs { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 32px; }',
  ".tab { display: flex; align-items: center; gap: 8px; background: var(--surface); border: 1px solid var(--border); color: var(--muted); font-family: 'JetBrains Mono', monospace; font-size: 11px; padding: 8px 14px; cursor: pointer; transition: all 0.15s; }",
  '.tab-dot { width: 7px; height: 7px; border-radius: 50%; background: currentColor; opacity: 0.45; transition: opacity 0.15s; }',
  '.tab-count { font-size: 10px; opacity: 0.45; }',
  '.tab:hover { color: var(--text); }',
  '.tab.active { border-color: var(--accent, var(--muted)); color: var(--accent, var(--text)); }',
  '.tab.active .tab-dot { opacity: 1; }',
  '',
  '/* STATS */',
  '.stats-bar { font-size: 10px; letter-spacing: 0.14em; text-transform: uppercase; color: var(--muted); margin-bottom: 20px; }',
  '.stats-bar strong { color: var(--text); font-weight: 500; }',
  '',
  '/* GROUP SECTIONS */',
  '.group-section { margin-bottom: 52px; }',
  '.group-heading { display: flex; align-items: baseline; gap: 12px; margin-bottom: 18px; padding-bottom: 14px; border-bottom: 1px solid var(--border); }',
  ".group-label { font-family: 'Syne', sans-serif; font-size: 18px; font-weight: 700; letter-spacing: -0.01em; }",
  '.group-badge { font-size: 10px; letter-spacing: 0.1em; text-transform: uppercase; padding: 3px 8px; border: 1px solid currentColor; opacity: 0.6; }',
  '.group-count { font-size: 11px; color: var(--muted); margin-left: auto; }',
  '',
  '/* CARDS */',
  '.cards { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 8px; }',
  '.card { display: flex; align-items: stretch; text-decoration: none; background: var(--surface); border: 1px solid var(--border); transition: border-color 0.15s, background 0.15s, transform 0.15s; animation: pop 0.3s ease both; overflow: hidden; position: relative; }',
  '@keyframes pop { from { opacity: 0; transform: translateY(6px) scale(0.98); } to { opacity: 1; transform: none; } }',
  '.card:hover { background: var(--surface2); transform: translateY(-2px); border-color: var(--card-accent); }',
  ".card::after { content: ''; position: absolute; left: 0; top: 0; bottom: 0; width: 3px; background: var(--card-accent); opacity: 0; transition: opacity 0.15s; }",
  '.card:hover::after { opacity: 1; }',
  ".card-id { font-size: 20px; font-weight: 300; font-family: 'Syne', sans-serif; color: var(--card-accent); min-width: 56px; display: flex; align-items: center; justify-content: center; border-right: 1px solid var(--border); padding: 0 12px; opacity: 0.8; }",
  '.card-body { padding: 14px 16px; flex: 1; display: flex; flex-direction: column; justify-content: center; }',
  '.card-name { font-size: 12px; font-weight: 500; color: var(--text); line-height: 1.45; letter-spacing: 0.01em; }',
  '.card-file { font-size: 10px; color: var(--muted); margin-top: 5px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }',
  '.card-arrow { display: flex; align-items: center; padding: 0 14px; color: var(--muted); font-size: 14px; transition: color 0.15s, transform 0.15s; }',
  '.card:hover .card-arrow { color: var(--card-accent); transform: translateX(3px); }',
  '',
  '#empty { display: none; text-align: center; padding: 80px 0; font-size: 12px; color: var(--muted); letter-spacing: 0.1em; }',
  '',
  'footer { border-top: 1px solid var(--border); padding-top: 20px; margin-top: 16px; display: flex; justify-content: space-between; font-size: 10px; color: var(--muted); letter-spacing: 0.1em; text-transform: uppercase; }',
  '',
  'mark { background: transparent; color: var(--card-accent, var(--text)); font-weight: 600; }',
  '',
  '@media (max-width: 600px) { .cards { grid-template-columns: 1fr; } h1 { font-size: 32px; } .controls { flex-direction: column; } }',
].join('\n');

// ─── script.js ────────────────────────────────────────────────────────────────
// Build as a string array to avoid template-literal escaping issues with
// the embedded regex special characters.
const js = [
  '/* script.js - generated by generate-index.js */',
  '',
  'const DATA = ' + JSON.stringify(groups, null, 2) + ';',
  '',
  "const ACCENTS = ['var(--c0)','var(--c1)','var(--c2)','var(--c3)','var(--c4)'];",
  '',
  '// STATE',
  "var activeGroup = 'all';",
  "var sortMode    = 'id';",
  "var query       = '';",
  '',
  '// REFS',
  "var searchEl   = document.getElementById('search');",
  "var statsEl    = document.getElementById('stats-count');",
  "var emptyEl    = document.getElementById('empty');",
  "var tabsEl     = document.getElementById('tabs');",
  "var sectionsEl = document.getElementById('sections');",
  '',
  'function init() { buildTabs(); buildSections(); render(); }',
  '',
  '// BUILD TABS',
  'function buildTabs() {',
  '  var total = DATA.reduce(function(s,g){ return s + g.items.length; }, 0);',
  "  tabsEl.appendChild(makeTab('all', 'All', total, null));",
  '  DATA.forEach(function(g, i) {',
  '    tabsEl.appendChild(makeTab(g.slug, g.name, g.items.length, ACCENTS[i % ACCENTS.length]));',
  '  });',
  '}',
  '',
  'function makeTab(slug, label, count, accent) {',
  "  var btn = document.createElement('button');",
  "  btn.className = 'tab' + (slug === 'all' ? ' active' : '');",
  '  btn.dataset.slug = slug;',
  "  if (accent) btn.style.setProperty('--accent', accent);",
  "  var dot = accent ? '<span class=\"tab-dot\" style=\"color:' + accent + '\"></span>' : '';",
  "  btn.innerHTML = dot + '<span>' + label + '</span><span class=\"tab-count\">' + count + '</span>';",
  "  btn.addEventListener('click', function() {",
  '    activeGroup = slug;',
  "    document.querySelectorAll('.tab').forEach(function(t){ t.classList.remove('active'); });",
  "    btn.classList.add('active');",
  '    render();',
  '  });',
  '  return btn;',
  '}',
  '',
  '// BUILD SECTIONS',
  'function buildSections() {',
  '  DATA.forEach(function(g, i) {',
  '    var accent = ACCENTS[i % ACCENTS.length];',
  "    var sec = document.createElement('div');",
  "    sec.className = 'group-section';",
  "    sec.id = 'sec-' + g.slug;",
  '    sec.innerHTML =',
  '      \'<div class="group-heading">\' +',
  "        '<span class=\"group-label\">' + g.name + '</span>' +",
  "        '<span class=\"group-badge\" style=\"color:' + accent + '\">' + g.slug + '</span>' +",
  '        \'<span class="group-count" id="cnt-\' + g.slug + \'"></span>\' +',
  "      '</div>' +",
  '      \'<div class="cards" id="cards-\' + g.slug + \'"></div>\';',
  '    sectionsEl.appendChild(sec);',
  '  });',
  '}',
  '',
  '// RENDER',
  'function render() {',
  '  var q = query.toLowerCase().trim();',
  '  var totalVisible = 0;',
  '',
  '  DATA.forEach(function(g, gi) {',
  '    var accent = ACCENTS[gi % ACCENTS.length];',
  "    var sec   = document.getElementById('sec-' + g.slug);",
  "    var grid  = document.getElementById('cards-' + g.slug);",
  "    var cntEl = document.getElementById('cnt-' + g.slug);",
  '',
  "    if (activeGroup !== 'all' && activeGroup !== g.slug) { sec.hidden = true; return; }",
  '',
  '    var items = g.items.filter(function(item) {',
  '      return !q ||',
  '        item.name.toLowerCase().includes(q) ||',
  '        item.id.includes(q) ||',
  '        item.file.toLowerCase().includes(q);',
  '    });',
  '',
  "    if (sortMode === 'name') {",
  '      items = items.slice().sort(function(a,b){ return a.name.localeCompare(b.name); });',
  '    } else {',
  '      items = items.slice().sort(function(a,b){ return parseInt(a.id) - parseInt(b.id); });',
  '    }',
  '',
  '    sec.hidden = items.length === 0;',
  '    totalVisible += items.length;',
  "    cntEl.textContent = items.length + ' file' + (items.length !== 1 ? 's' : '');",
  '',
  "    grid.innerHTML = '';",
  '    items.forEach(function(item, idx) {',
  "      var a = document.createElement('a');",
  "      a.className = 'card';",
  '      a.href = item.file;',
  "      a.style.cssText = '--card-accent:' + accent + '; animation-delay:' + (idx * 30) + 'ms';",
  "      var hi = q ? item.name.replace(new RegExp(escRe(q), 'gi'), '<mark>$&</mark>') : item.name;",
  '      a.innerHTML =',
  "        '<div class=\"card-id\">' + item.id + '</div>' +",
  '        \'<div class="card-body">\' +',
  "          '<div class=\"card-name\">' + hi + '</div>' +",
  "          '<div class=\"card-file\">' + item.file + '</div>' +",
  "        '</div>' +",
  '        \'<div class="card-arrow">&#x2192;</div>\';',
  '      grid.appendChild(a);',
  '    });',
  '  });',
  '',
  '  statsEl.textContent = totalVisible;',
  "  emptyEl.style.display = totalVisible === 0 ? 'block' : 'none';",
  '}',
  '',
  'function escRe(s) {',
  "  return s.replace(/[-[\\]{}()*+?.,\\\\^$|#\\s]/g, '\\\\$&');",
  '}',
  '',
  '// EVENTS',
  "document.querySelectorAll('.sort-btn').forEach(function(btn) {",
  "  btn.addEventListener('click', function() {",
  '    sortMode = btn.dataset.sort;',
  "    document.querySelectorAll('.sort-btn').forEach(function(b){ b.classList.remove('active'); });",
  "    btn.classList.add('active');",
  '    render();',
  '  });',
  '});',
  '',
  "searchEl.addEventListener('input', function(e) {",
  '  query = e.target.value;',
  '  render();',
  '});',
  '',
  "document.addEventListener('keydown', function(e) {",
  "  if (e.key === '/' && document.activeElement !== searchEl) {",
  '    e.preventDefault(); searchEl.focus();',
  '  }',
  "  if (e.key === 'Escape') searchEl.blur();",
  '});',
  '',
  "document.getElementById('footer-date').textContent =",
  "  new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long' });",
  '',
  'init();',
].join('\n');

// ─── WRITE FILES ──────────────────────────────────────────────────────────────
fs.writeFileSync('index.html', html, 'utf8');
fs.writeFileSync('style.css', css, 'utf8');
fs.writeFileSync('script.js', js, 'utf8');

console.log('\n\u2705  Generated:');
console.log('   index.html');
console.log('   style.css');
console.log('   script.js');
console.log('\nOpen index.html in a browser or deploy the whole folder.\n');
