/* script.js - generated by generate-index.js */

const DATA = [
  {
    "slug": "genai-system-design-interview",
    "name": "Genai System Design Interview",
    "items": [
      {
        "id": "01",
        "name": "Introduction And Overview",
        "file": "genai-system-design-interview-01-introduction-and-overview.html"
      },
      {
        "id": "02",
        "name": "Gmail Smart Compose",
        "file": "genai-system-design-interview-02-gmail-smart-compose.html"
      },
      {
        "id": "03",
        "name": "Google Translate",
        "file": "genai-system-design-interview-03-google-translate.html"
      },
      {
        "id": "04",
        "name": "Chatgpt Personal Assistant Chatbot",
        "file": "genai-system-design-interview-04-chatgpt-personal-assistant-chatbot.html"
      },
      {
        "id": "05",
        "name": "Image Captioning",
        "file": "genai-system-design-interview-05-image-captioning.html"
      },
      {
        "id": "06",
        "name": "Retrieval Augmented Generation",
        "file": "genai-system-design-interview-06-retrieval-augmented-generation.html"
      },
      {
        "id": "07",
        "name": "Realistic Face Generation",
        "file": "genai-system-design-interview-07-realistic-face-generation.html"
      },
      {
        "id": "08",
        "name": "High Resolution Image Synthesis",
        "file": "genai-system-design-interview-08-high-resolution-image-synthesis.html"
      },
      {
        "id": "09",
        "name": "Text To Image Generation",
        "file": "genai-system-design-interview-09-text-to-image-generation.html"
      },
      {
        "id": "10",
        "name": "Personalized Headshot Generation",
        "file": "genai-system-design-interview-10-personalized-headshot-generation.html"
      },
      {
        "id": "11",
        "name": "Text To Video Generation",
        "file": "genai-system-design-interview-11-text-to-video-generation.html"
      }
    ]
  },
  {
    "slug": "machine-learning-system-design-interview",
    "name": "Machine Learning System Design Interview",
    "items": [
      {
        "id": "01",
        "name": "Introduction And Overview",
        "file": "machine-learning-system-design-interview-01-introduction-and-overview.html"
      },
      {
        "id": "02",
        "name": "Visual Search System",
        "file": "machine-learning-system-design-interview-02-visual-search-system.html"
      },
      {
        "id": "03",
        "name": "Google Street View Blurring System",
        "file": "machine-learning-system-design-interview-03-google-street-view-blurring-system.html"
      },
      {
        "id": "04",
        "name": "Youtube Video Search",
        "file": "machine-learning-system-design-interview-04-youtube-video-search.html"
      },
      {
        "id": "05",
        "name": "Harmful Content Detection",
        "file": "machine-learning-system-design-interview-05-harmful-content-detection.html"
      },
      {
        "id": "06",
        "name": "Video Recommendation System",
        "file": "machine-learning-system-design-interview-06-video-recommendation-system.html"
      },
      {
        "id": "07",
        "name": "Event Recommendation System",
        "file": "machine-learning-system-design-interview-07-event-recommendation-system.html"
      },
      {
        "id": "08",
        "name": "Ad Click Prediction On Social Platforms",
        "file": "machine-learning-system-design-interview-08-ad-click-prediction-on-social-platforms.html"
      },
      {
        "id": "09",
        "name": "Similar Listings On Vacation Rental Platforms",
        "file": "machine-learning-system-design-interview-09-similar-listings-on-vacation-rental-platforms.html"
      },
      {
        "id": "10",
        "name": "Personalized News Feed",
        "file": "machine-learning-system-design-interview-10-personalized-news-feed.html"
      },
      {
        "id": "11",
        "name": "People You May Know",
        "file": "machine-learning-system-design-interview-11-people-you-may-know.html"
      }
    ]
  },
  {
    "slug": "mobile-system-design-interview",
    "name": "Mobile System Design Interview",
    "items": [
      {
        "id": "01",
        "name": "Introduction",
        "file": "mobile-system-design-interview-01-introduction.html"
      },
      {
        "id": "02",
        "name": "A Framework For Mobile Sd Interviews",
        "file": "mobile-system-design-interview-02-a-framework-for-mobile-sd-interviews.html"
      },
      {
        "id": "03",
        "name": "News Feed App",
        "file": "mobile-system-design-interview-03-news-feed-app.html"
      },
      {
        "id": "04",
        "name": "Chat App",
        "file": "mobile-system-design-interview-04-chat-app.html"
      },
      {
        "id": "05",
        "name": "Stock Trading App",
        "file": "mobile-system-design-interview-05-stock-trading-app.html"
      },
      {
        "id": "06",
        "name": "Pagination Library",
        "file": "mobile-system-design-interview-06-pagination-library.html"
      },
      {
        "id": "07",
        "name": "Hotel Reservation App",
        "file": "mobile-system-design-interview-07-hotel-reservation-app.html"
      },
      {
        "id": "08",
        "name": "Google Drive App",
        "file": "mobile-system-design-interview-08-google-drive-app.html"
      },
      {
        "id": "09",
        "name": "Youtube App",
        "file": "mobile-system-design-interview-09-youtube-app.html"
      },
      {
        "id": "10",
        "name": "Mobile System Design Building Blocks",
        "file": "mobile-system-design-interview-10-mobile-system-design-building-blocks.html"
      },
      {
        "id": "11",
        "name": "Quick Reference Cheat Sheet For Msd Interview",
        "file": "mobile-system-design-interview-11-quick-reference-cheat-sheet-for-msd-interview.html"
      }
    ]
  },
  {
    "slug": "system-design-interview",
    "name": "System Design Interview",
    "items": [
      {
        "id": "02",
        "name": "Scale From Zero To Millions Of Users",
        "file": "system-design-interview-02-scale-from-zero-to-millions-of-users.html"
      },
      {
        "id": "03",
        "name": "Back Of The Envelope Estimation",
        "file": "system-design-interview-03-back-of-the-envelope-estimation.html"
      },
      {
        "id": "04",
        "name": "A Framework For System Design Interviews",
        "file": "system-design-interview-04-a-framework-for-system-design-interviews.html"
      },
      {
        "id": "05",
        "name": "Design A Rate Limiter",
        "file": "system-design-interview-05-design-a-rate-limiter.html"
      },
      {
        "id": "06",
        "name": "Design Consistent Hashing",
        "file": "system-design-interview-06-design-consistent-hashing.html"
      },
      {
        "id": "07",
        "name": "Design A Key Value Store",
        "file": "system-design-interview-07-design-a-key-value-store.html"
      },
      {
        "id": "08",
        "name": "Design A Unique Id Generator In Distributed Systems",
        "file": "system-design-interview-08-design-a-unique-id-generator-in-distributed-systems.html"
      },
      {
        "id": "09",
        "name": "Design A Url Shortener",
        "file": "system-design-interview-09-design-a-url-shortener.html"
      },
      {
        "id": "10",
        "name": "Design A Web Crawler",
        "file": "system-design-interview-10-design-a-web-crawler.html"
      },
      {
        "id": "11",
        "name": "Design A Notification System",
        "file": "system-design-interview-11-design-a-notification-system.html"
      },
      {
        "id": "12",
        "name": "Design A News Feed System",
        "file": "system-design-interview-12-design-a-news-feed-system.html"
      },
      {
        "id": "13",
        "name": "Design A Chat System",
        "file": "system-design-interview-13-design-a-chat-system.html"
      },
      {
        "id": "14",
        "name": "Design A Search Autocomplete System",
        "file": "system-design-interview-14-design-a-search-autocomplete-system.html"
      },
      {
        "id": "15",
        "name": "Design Youtube",
        "file": "system-design-interview-15-design-youtube.html"
      },
      {
        "id": "16",
        "name": "Design Google Drive",
        "file": "system-design-interview-16-design-google-drive.html"
      },
      {
        "id": "17",
        "name": "Proximity Service",
        "file": "system-design-interview-17-proximity-service.html"
      },
      {
        "id": "18",
        "name": "Nearby Friends",
        "file": "system-design-interview-18-nearby-friends.html"
      },
      {
        "id": "19",
        "name": "Google Maps",
        "file": "system-design-interview-19-google-maps.html"
      },
      {
        "id": "20",
        "name": "Distributed Message Queue",
        "file": "system-design-interview-20-distributed-message-queue.html"
      },
      {
        "id": "21",
        "name": "Metrics Monitoring And Alerting System",
        "file": "system-design-interview-21-metrics-monitoring-and-alerting-system.html"
      },
      {
        "id": "22",
        "name": "Ad Click Event Aggregation",
        "file": "system-design-interview-22-ad-click-event-aggregation.html"
      },
      {
        "id": "23",
        "name": "Hotel Reservation System",
        "file": "system-design-interview-23-hotel-reservation-system.html"
      },
      {
        "id": "24",
        "name": "Distributed Email Service",
        "file": "system-design-interview-24-distributed-email-service.html"
      },
      {
        "id": "25",
        "name": "S3 Like Object Storage",
        "file": "system-design-interview-25-s3-like-object-storage.html"
      },
      {
        "id": "26",
        "name": "Real Time Gaming Leaderboard",
        "file": "system-design-interview-26-real-time-gaming-leaderboard.html"
      },
      {
        "id": "27",
        "name": "Payment System",
        "file": "system-design-interview-27-payment-system.html"
      },
      {
        "id": "28",
        "name": "Digital Wallet",
        "file": "system-design-interview-28-digital-wallet.html"
      },
      {
        "id": "29",
        "name": "Stock Exchange",
        "file": "system-design-interview-29-stock-exchange.html"
      },
      {
        "id": "30",
        "name": "The Learning Continues",
        "file": "system-design-interview-30-the-learning-continues.html"
      }
    ]
  }
];

const ACCENTS = ['var(--c0)','var(--c1)','var(--c2)','var(--c3)','var(--c4)'];

// STATE
var activeGroup = 'all';
var sortMode    = 'id';
var query       = '';

// REFS
var searchEl   = document.getElementById('search');
var statsEl    = document.getElementById('stats-count');
var emptyEl    = document.getElementById('empty');
var tabsEl     = document.getElementById('tabs');
var sectionsEl = document.getElementById('sections');

function init() { buildTabs(); buildSections(); render(); }

// BUILD TABS
function buildTabs() {
  var total = DATA.reduce(function(s,g){ return s + g.items.length; }, 0);
  tabsEl.appendChild(makeTab('all', 'All', total, null));
  DATA.forEach(function(g, i) {
    tabsEl.appendChild(makeTab(g.slug, g.name, g.items.length, ACCENTS[i % ACCENTS.length]));
  });
}

function makeTab(slug, label, count, accent) {
  var btn = document.createElement('button');
  btn.className = 'tab' + (slug === 'all' ? ' active' : '');
  btn.dataset.slug = slug;
  if (accent) btn.style.setProperty('--accent', accent);
  var dot = accent ? '<span class="tab-dot" style="color:' + accent + '"></span>' : '';
  btn.innerHTML = dot + '<span>' + label + '</span><span class="tab-count">' + count + '</span>';
  btn.addEventListener('click', function() {
    activeGroup = slug;
    document.querySelectorAll('.tab').forEach(function(t){ t.classList.remove('active'); });
    btn.classList.add('active');
    render();
  });
  return btn;
}

// BUILD SECTIONS
function buildSections() {
  DATA.forEach(function(g, i) {
    var accent = ACCENTS[i % ACCENTS.length];
    var sec = document.createElement('div');
    sec.className = 'group-section';
    sec.id = 'sec-' + g.slug;
    sec.innerHTML =
      '<div class="group-heading">' +
        '<span class="group-label">' + g.name + '</span>' +
        '<span class="group-badge" style="color:' + accent + '">' + g.slug + '</span>' +
        '<span class="group-count" id="cnt-' + g.slug + '"></span>' +
      '</div>' +
      '<div class="cards" id="cards-' + g.slug + '"></div>';
    sectionsEl.appendChild(sec);
  });
}

// RENDER
function render() {
  var q = query.toLowerCase().trim();
  var totalVisible = 0;

  DATA.forEach(function(g, gi) {
    var accent = ACCENTS[gi % ACCENTS.length];
    var sec   = document.getElementById('sec-' + g.slug);
    var grid  = document.getElementById('cards-' + g.slug);
    var cntEl = document.getElementById('cnt-' + g.slug);

    if (activeGroup !== 'all' && activeGroup !== g.slug) { sec.hidden = true; return; }

    var items = g.items.filter(function(item) {
      return !q ||
        item.name.toLowerCase().includes(q) ||
        item.id.includes(q) ||
        item.file.toLowerCase().includes(q);
    });

    if (sortMode === 'name') {
      items = items.slice().sort(function(a,b){ return a.name.localeCompare(b.name); });
    } else {
      items = items.slice().sort(function(a,b){ return parseInt(a.id) - parseInt(b.id); });
    }

    sec.hidden = items.length === 0;
    totalVisible += items.length;
    cntEl.textContent = items.length + ' file' + (items.length !== 1 ? 's' : '');

    grid.innerHTML = '';
    items.forEach(function(item, idx) {
      var a = document.createElement('a');
      a.className = 'card';
      a.href = item.file;
      a.style.cssText = '--card-accent:' + accent + '; animation-delay:' + (idx * 30) + 'ms';
      var hi = q ? item.name.replace(new RegExp(escRe(q), 'gi'), '<mark>$&</mark>') : item.name;
      a.innerHTML =
        '<div class="card-id">' + item.id + '</div>' +
        '<div class="card-body">' +
          '<div class="card-name">' + hi + '</div>' +
          '<div class="card-file">' + item.file + '</div>' +
        '</div>' +
        '<div class="card-arrow">&#x2192;</div>';
      grid.appendChild(a);
    });
  });

  statsEl.textContent = totalVisible;
  emptyEl.style.display = totalVisible === 0 ? 'block' : 'none';
}

function escRe(s) {
  return s.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, '\\$&');
}

// EVENTS
document.querySelectorAll('.sort-btn').forEach(function(btn) {
  btn.addEventListener('click', function() {
    sortMode = btn.dataset.sort;
    document.querySelectorAll('.sort-btn').forEach(function(b){ b.classList.remove('active'); });
    btn.classList.add('active');
    render();
  });
});

searchEl.addEventListener('input', function(e) {
  query = e.target.value;
  render();
});

document.addEventListener('keydown', function(e) {
  if (e.key === '/' && document.activeElement !== searchEl) {
    e.preventDefault(); searchEl.focus();
  }
  if (e.key === 'Escape') searchEl.blur();
});

document.getElementById('footer-date').textContent =
  new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long' });

init();